/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrame_BenefitReport.java
 *
 * Created on Dec 17, 2011, 11:08:51 PM
 */
package com.wb.view;

import com.wb.control.MyiReportViewer;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author Lahiru
 */
public class MIN_Report extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_BenefitReport
     */
    public MIN_Report() {
        initComponents();
        jProgressBar1.setVisible(false);
        jLabel_PleaseWait.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel_PleaseWait = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTextField_s_id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chilling Center Details Report");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBar1.setBackground(new java.awt.Color(255, 255, 102));
        jProgressBar1.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 220, -1));

        jLabel_PleaseWait.setText("Please wait ..");
        getContentPane().add(jLabel_PleaseWait, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 70, 10));

        jDesktopPane1.setLayout(null);
        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 950, 520));

        jTextField_s_id.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        getContentPane().add(jTextField_s_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 110, 22));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(45, 44, 44));
        jLabel6.setText("MIN No");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 70, 20));

        jButton1.setText("View Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        setSize(new java.awt.Dimension(1017, 708));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void checkchildrenReport(String supid) {

    }
    public class thread2 implements Runnable {

        public void run() {

            String s = jTextField_s_id.getText();
            if (s.length() > 0) {
                HashMap param = new HashMap();
                param.put("MIN_No", s);

                MyiReportViewer viewer = new MyiReportViewer("/Users/anuruddha/Repos/NWSInventory/Inventory/src/Reports/MIN.jrxml", param);
                viewer.setBounds(0, 0, 950, 521);

                viewer.setVisible(true);
                jDesktopPane1.add(viewer);

                // ReportFile = "Details of Indent " + Indent_id_for_report;
            } else {
                JOptionPane.showMessageDialog(null, "Please Enter a valid MIN No", "Invalid MIN NO", JOptionPane.ERROR_MESSAGE);
            }

        }
    }
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jDesktopPane1.removeAll();        // TODO add your handling code here:

        if (jTextField_s_id.getText().toString().isEmpty()) {
            return;
        }

        jDesktopPane1.removeAll();
        jProgressBar1.setVisible(true);
        jLabel_PleaseWait.setVisible(true);

        //Create all components
        //********************************************************************************
        new Thread(new Runnable() { // For Progress bar

            public void run() {

                int j = MyiReportViewer.i = 0;

                jLabel_PleaseWait.setVisible(true);
                jProgressBar1.setVisible(true);
                while (j < 100) {

                    j = MyiReportViewer.i;
                    jProgressBar1.setValue(j); //Set value
                    jProgressBar1.repaint();//Refresh graphics
                    try {
                        Thread.sleep(10);
                    } //Sleep 50 milliseconds
                    catch (InterruptedException err) {
                    }
                }
                jProgressBar1.setVisible(false);
                jLabel_PleaseWait.setVisible(false);

            }
        }).start();
        //*********************************************************************************
        //Start the thread
        new Thread(new thread2()).start(); //Start the thread for Indent Report (method is up ^)

        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new MIN_Report().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_PleaseWait;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField_s_id;
    // End of variables declaration//GEN-END:variables
}
